// Code generated by bowbuffer.gen.go.tmpl. DO NOT EDIT.

package bow

import (
	"fmt"
)

func NewBuffer(size int, typ Type, nullable bool) Buffer {
	var valid []bool
	if nullable {
		valid = make([]bool, size)
	}
	switch typ {
	case Int64:
		return Buffer{
			Value: make([]int64, size),
			Valid: valid,
		}
	case Float64:
		return Buffer{
			Value: make([]float64, size),
			Valid: valid,
		}
	case String:
		return Buffer{
			Value: make([]string, size),
			Valid: valid,
		}
	case Bool:
		return Buffer{
			Value: make([]bool, size),
			Valid: valid,
		}
	default:
		panic(fmt.Errorf("bow.NewBuffer: unsupported type %v", typ))
	}
}
