version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.16

    steps:
      - checkout

      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}

      - run:
          name: TESTS
          command: |
            go get github.com/jstemmer/go-junit-report
            bash -c ./scripts/test.sh

      - run:
          name: BENCHMARKS
          command: |
            go get golang.org/x/perf/cmd/benchstat
            bash -c ./scripts/benchmark.sh

      - store_artifacts:
          path: /tmp/benchmarks

      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
