name: CI

on: [push, pull_request]

jobs:
  base:
    runs-on: ubuntu-latest
    env:
      BENCH_RESULTS_DIR_PATH: benchmarks
      BENCH_RESULTS_FILE_PATH: ${{ format('benchmarks/{0}.txt', github.sha) }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Run tests
        run: |
          go get github.com/jstemmer/go-junit-report
          bash -c ./scripts/test.sh

      - name: Run benchmarks
        run: |
          go get golang.org/x/perf/cmd/benchstat
          bash -c ./scripts/benchmark.sh

      - name: Upload artifact of current branch benchmark results
        uses: actions/upload-artifact@v2
        with:
          name: current-branch-benchmark-results
          path: ${{ env.BENCH_RESULTS_FILE_PATH }}

  compare-benchmarks:
    if: ${{ github.event_name == 'pull_request' }}
    needs: base
    runs-on: ubuntu-latest
    env:
      BENCH_RESULTS_CURR_FILE_PATH: ${{ format('benchmarks/{0}.txt', github.sha) }}
      BENCH_RESULTS_DIR_PATH: benchmarks
      BENCH_RESULTS_FILE_PATH: ${{ format('benchmarks/{0}.txt', github.base_ref) }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.base_ref }}

      - uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - uses: actions/download-artifact@v2
        with:
          name: current-branch-benchmark-results

      - name: Display structure of downloaded files
        run: ls -R

      - name: ${{ format('Run benchmarks on {0}', github.base_ref) }}
        run: |
          go get golang.org/x/perf/cmd/benchstat
          bash -c ./scripts/benchmark.sh

      - name: Compare benchmarks
        run: |
          bash -c ./scripts/benchstat.sh $BENCH_RESULTS_FILE_PATH $BENCH_RESULTS_CURR_FILE_PATH

      - name: Upload artifact of base branch benchmark results
        uses: actions/upload-artifact@v2
        with:
          name: base-branch-benchmark-results
          path: ${{ env.BENCH_RESULTS_FILE_PATH }}
