name: CI

on: [push, pull_request]

jobs:
  current-branch:
    runs-on: ubuntu-latest
    env:
      BENCH_RESULTS_DIR_PATH: benchmarks
      BENCH_COMPARISON_FILE_PATH: ${{ format('benchmarks/comparison-{0}-vs-{1}.txt', github.base_ref, github.sha) }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Run tests
        run: |
          go install github.com/jstemmer/go-junit-report@latest
          bash -c ./scripts/test.sh

      - name: ${{ format('Run benchmarks on {0}', github.sha) }}
        run: |
          go install golang.org/x/perf/cmd/benchstat@latest
          bash -c ./scripts/benchmark.sh "benchmarks" "${{ format('benchmarks/{0}.txt', github.sha) }}" 

      - name: ${{ format('Uploading artifact of branch {0} benchmark results', github.sha) }}
        uses: actions/upload-artifact@v2
        with:
          name: ${{ format('{0}-branch-benchmark-results', github.sha) }}
          path: ${{ format('benchmarks/{0}.txt', github.sha) }}

      - uses: actions/checkout@v2
        if: ${{ github.event_name == 'pull_request' }}
        with:
          ref: ${{ github.base_ref }}

      - name: ${{ format('Run benchmarks on {0}', github.base_ref) }}
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          bash -c ./scripts/benchmark.sh "benchmarks" "${{ format('benchmarks/{0}.txt', github.base_ref) }}" 

      - name: ${{ format('Uploading artifact of branch {0} benchmark results', github.base_ref) }}
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/upload-artifact@v2
        with:
          name: ${{ format('{0}-branch-benchmark-results', github.base_ref) }}
          path: ${{ format('benchmarks/{0}.txt', github.base_ref) }}

      - name: ${{ format('Compare benchmarks of old branch {0} with new branch {1}', github.base_ref, github.sha) }}
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          bash ./scripts/benchstat.sh "${{ format('benchmarks/{0}.txt', github.base_ref) }}" "${{ format('benchmarks/{0}.txt', github.sha) }}" 

      - name: Upload artifact of benchmark comparison results
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/upload-artifact@v2
        with:
          name: benchmark-comparison-results
          path: ${{ format('benchmarks/comparison-{0}-vs-{1}.txt', github.base_ref, github.sha) }}