name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Tests
        run: |
          go get github.com/jstemmer/go-junit-report
          bash -c ./scripts/test.sh

      - name: Benchmarks
        run: |
          go get golang.org/x/perf/cmd/benchstat
          bash -c ./scripts/benchmark.sh

      - name: Archive benchmarks results
        uses: actions/upload-artifact@v2
        with:
          name: archive-benchmarks-results
          path: /tmp/benchmarks
