name: CI

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      BENCH_RESULTS_DIR_PATH: benchmarks
      BENCH_COMPARISON_FILE_PATH: ${{ format('benchmarks/comparison-{0}-vs-{1}.txt', github.base_ref, github.sha) }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Run tests
        run: |
          go install github.com/jstemmer/go-junit-report@latest
          bash -c ./scripts/test.sh

      - name: ${{ format('Run benchmarks on sha {0}', github.sha) }}
        run: |
          go install golang.org/x/perf/cmd/benchstat@latest
          bash ./scripts/benchmark.sh
        env:
          BENCH_RESULTS_FILE_PATH: ${{ format('benchmarks/{0}.txt', github.sha) }}

      - name: ${{ format('Uploading artifact of sha {0} benchmark results', github.sha) }}
        uses: actions/upload-artifact@v2
        with:
          name: ${{ format('{0}-sha-benchmark-results', github.sha) }}
          path: ${{ format('benchmarks/{0}.txt', github.sha) }}

      - uses: actions/checkout@v3
        if: ${{ github.event_name == 'pull_request' }}
        with:
          ref: ${{ github.base_ref }}

      - uses: actions/download-artifact@v2
        if: ${{ github.event_name == 'pull_request' }}
        with:
          name: ${{ format('{0}-sha-benchmark-results', github.sha) }}
          path: benchmarks

      - name: ${{ format('Run benchmarks on base ref {0}', github.base_ref) }}
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          bash ./scripts/benchmark.sh
        env:
          BENCH_RESULTS_FILE_PATH: ${{ format('benchmarks/{0}.txt', github.base_ref) }}

      - name: ${{ format('Uploading artifact of base ref {0} benchmark results', github.base_ref) }}
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/upload-artifact@v2
        with:
          name: ${{ format('{0}-base-ref-benchmark-results', github.base_ref) }}
          path: ${{ format('benchmarks/{0}.txt', github.base_ref) }}

      - name: ${{ format('Compare benchmarks of base ref {0} with sha {1}', github.base_ref, github.sha) }}
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          bash ./scripts/benchstat.sh "${{ format('benchmarks/{0}.txt', github.base_ref) }}" "${{ format('benchmarks/{0}.txt', github.sha) }}" 

      - name: Upload artifact of benchmark comparison results
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/upload-artifact@v2
        with:
          name: benchmark-comparison-results
          path: ${{ format('benchmarks/comparison-{0}-vs-{1}.txt', github.base_ref, github.sha) }}
