name: CI

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      BENCH_RESULTS_DIR_PATH: benchmarks
      BENCH_COMPARISON_FILE_PATH: ${{ format('benchmarks/comparison-{0}-vs-{1}.txt', github.base_ref, github.sha) }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Run tests
        run: |
          go install github.com/jstemmer/go-junit-report@latest
          bash -c ./scripts/test.sh
