name: ci

on: [push, pull_request]

jobs:
  base:
    runs-on: ubuntu-latest
    env:
      BENCH_RESULTS_DIR_PATH: ${{ format('{0}/benchmarks', runner.temp) }}
      BENCH_RESULTS_FILE_PATH: ${{ format('{0}/benchmarks/{1}.txt', runner.temp, github.sha) }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Test
        run: |
          go get github.com/jstemmer/go-junit-report
          bash -c ./scripts/test.sh

      - name: Benchmark
        run: |
          go get golang.org/x/perf/cmd/benchstat
          bash -c ./scripts/benchmark.sh

      - name: Archive current benchmark results
        uses: actions/upload-artifact@v2
        with:
          name: current-benchmark-results
          path: $BENCH_RESULTS_FILE_PATH

  compare-benchmarks:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    env:
      BENCH_RESULTS_CURR_FILE_PATH: ${{ format('{0}/benchmarks/{1}.txt', runner.temp, github.sha) }}
      BENCH_RESULTS_DIR_PATH: ${{ format('{0}/benchmarks', runner.temp) }}
      BENCH_RESULTS_FILE_PATH: ${{ format('{0}/benchmarks/{1}.{2}.txt', runner.temp, github.base_ref, github.sha) }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: $GITHUB_BASE_REF

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Benchmarks on $GITHUB_BASE_REF
        run: |
          go get golang.org/x/perf/cmd/benchstat
          bash -c ./scripts/benchmark.sh

      - name: Download current benchmark results
        uses: actions/download-artifact@v2
        with:
          name: current-benchmark-results

      - name: Compare benchmarks
        run: |
          bash ./scripts/benchstat.sh $BENCH_RESULTS_FILE_PATH $BENCH_RESULTS_CURR_FILE_PATH

      - name: Archive base benchmark results
        uses: actions/upload-artifact@v2
        with:
          name: base-benchmark-results
          path: $BENCH_RESULTS_FILE_PATH